From jupyterhub/singleuser

MAINTAINER Brockmann Consult GmbH <http://www.brockmann-consult.de>

RUN conda install --quiet --yes 'xarray' 'dask'

#USER root

# Install Julia.
#RUN apt-get update
#RUN apt-get -y install software-properties-common
#RUN add-apt-repository -y ppa:staticfloat/juliareleases
#RUN add-apt-repository -y ppa:staticfloat/julia-deps
#RUN apt-get update
#RUN apt-get install -y julia
#RUN rm -rf /var/lib/apt/lists/*
